# Generated by Django 5.2 on 2025-10-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='full_name',
            field=models.CharField(blank=True),
        ),
    ]
