# Generated by Django 5.2 on 2025-10-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0002_participant_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(help_text='Die Email-Adresse ist erforderlich!', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(help_text='Der Vorname ist erforderlich!', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(help_text='Der Nachname ist erforderlich!', max_length=100),
        ),
    ]
